In [1]:
import pandas as pd
import numpy as np
import time
from datetime import date
import matplotlib.pyplot as plt
import seaborn as sns
pd.set_option('display.max_columns', None)
import re

# Importing the main dataset

In [2]:
status = pd.read_excel("Raw Data/Legal Status.xlsx", sheet_name = "Tabelle1")
status

              State      Online   In-Person
0           Alabama           X           X
1            Alaska           X           X
2           Arizona           ?           ?
3          Arkansas           ?           ?
4        California           X           X
5          Colorado           ?           ?
6       Connecticut           ?           ?
7          Delaware           X           ?
8           Florida           X           X
9           Georgia           X           X
10           Hawaii           X           X
11            Idaho           X           X
12         Illinois           ?           ?
13          Indiana           ?           ?
14             Iowa           ?           ?
15           Kansas           ?           ?
16         Kentucky           X           X
17        Louisiana           ?           ?
18            Maine     Pending     Pending
19         Maryland           ?           ?
20    Massachusetts  March 2023  Early 2023
21         Michigan           ?           ?
22        Minnesota           X           X
23      Mississippi           X           ?
24         Missouri           X           X
25          Montana           X           ?
26         Nebraska           X     Pending
27           Nevada           ?           ?
28    New Hampshire           ?           ?
29       New Jersey           ?           ?
30       New Mexico           X           ?
31         New York           ?           ?
32   North Carolina           X           ?
33     North Dakota           X           ?
34             Ohio           ?           ?
35         Oklahoma           X           X
36           Oregon           ?           ?
37     Pennsylvania           ?           ?
38     Rhode Island           ?           ?
39   South Carolina           X           X
40     South Dakota           X           ?
41        Tennessee           ?           X
42            Texas           X           X
43             Utah           X           X
44          Vermont           X           X
45         Virginia           ?           ?
46       Washington           X           ?
47  Washington D.C.           ?           ?
48    West Virginia           ?           ?
49        Wisconsin           X           ?
50          Wyoming           ?           X

Convert columns to snakecase

In [3]:
cols = []
for column in status.columns:
    cols.append(column.lower())
status.columns = cols

status = status.rename(columns={'in-person':'in_person'})

Thats a quick one, ? means the according type of spors betting is legal, everything else means basically not legal.
We map it with 0 for not legal and 1 for legal.

In [4]:
def legal(x):
    if x == '?':
        return 1
    return 0

In [5]:
status['online'] = status['online'].apply(legal)
status['in_person'] = status['in_person'].apply(legal)

In [6]:
status

              state  online  in_person
0           Alabama       0          0
1            Alaska       0          0
2           Arizona       1          1
3          Arkansas       1          1
4        California       0          0
5          Colorado       1          1
6       Connecticut       1          1
7          Delaware       0          1
8           Florida       0          0
9           Georgia       0          0
10           Hawaii       0          0
11            Idaho       0          0
12         Illinois       1          1
13          Indiana       1          1
14             Iowa       1          1
15           Kansas       1          1
16         Kentucky       0          0
17        Louisiana       1          1
18            Maine       0          0
19         Maryland       1          1
20    Massachusetts       0          0
21         Michigan       1          1
22        Minnesota       0          0
23      Mississippi       0          1
24         Missouri       0          0
25          Montana       0          1
26         Nebraska       0          0
27           Nevada       1          1
28    New Hampshire       1          1
29       New Jersey       1          1
30       New Mexico       0          1
31         New York       1          1
32   North Carolina       0          1
33     North Dakota       0          1
34             Ohio       1          1
35         Oklahoma       0          0
36           Oregon       1          1
37     Pennsylvania       1          1
38     Rhode Island       1          1
39   South Carolina       0          0
40     South Dakota       0          1
41        Tennessee       1          0
42            Texas       0          0
43             Utah       0          0
44          Vermont       0          0
45         Virginia       1          1
46       Washington       0          1
47  Washington D.C.       1          1
48    West Virginia       1          1
49        Wisconsin       0          1
50          Wyoming       1          0

# Saving

In [7]:
# As csv
status.to_csv('Clean Data/status.csv', index=False)